#!/usr/bin/expect

set timeout 20
set password "1"

set start [lindex $argv 0]
set end [lindex $argv 1]
set ipBase "192.168.7."

set hosts ""
for {set i $start} {$i <= $end} {incr i} {
    lappend hosts $ipBase$i
}

foreach host $hosts {
    spawn ssh-copy-id -i /root/.ssh/id_rsa.pub root@$host
    expect {
        "yes/no" { send "yes\r"; exp_continue }
        "password:" { send "$password\r" }
    }
    expect eof
}
